version: 2

build:
    image: testing

sphinx:
    builder: html
    configuration: docs/source/conf.py
    # fail_on_warning: true

python:
    version: "3.11"
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
