# Generated by Django 4.2.5 on 2023-11-23 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerTeamLink",
            new_name="TeamMembership",
        ),
    ]
