# Generated by Django 4.2.5 on 2023-12-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["game", "name", "handicap"],
                "verbose_name_plural": "teams",
            },
        ),
        migrations.AlterField(
            model_name="playermembership",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dashboard.team",
            ),
        ),
    ]
