# Generated by Django 4.2.5 on 2023-11-23 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_holescore_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holescore",
            name="team",
        ),
    ]
