# Generated by Django 4.2.5 on 2023-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_game_game_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="buy_in",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("best-ball", "Best Ball"),
                    ("stroke", "Stroke"),
                    ("skins", "Skins"),
                    ("stroke-skins", "Stroke w/Skins"),
                    ("best-ball-skins", "Best Ball w/Skins"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
