# Generated by Django 4.2.5 on 2023-12-27 12:33

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_game_buy_in_alter_game_game_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="buy_in_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="buy_in",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("10"),
                default_currency="USD",
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(5),
                    djmoney.models.validators.MaxMoneyValidator(100),
                ],
                verbose_name="Per-player buy-in",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("best-ball", "Best Ball"),
                    ("stroke", "Stroke"),
                    ("skins", "Skins"),
                    ("stroke-skins", "Stroke w/Skins"),
                    ("best-ball-skins", "Best Ball w/Skins"),
                ],
                default="best-ball",
                max_length=32,
            ),
        ),
    ]
