# Generated by Django 4.2.5 on 2023-11-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_remove_holescore_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="holescore",
            name="team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.teammembership",
            ),
        ),
    ]
