# Generated by Django 4.2.5 on 2023-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_holescore_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"], "verbose_name_plural": "teams"},
        ),
        migrations.RemoveField(
            model_name="holescore",
            name="team",
        ),
        migrations.RemoveField(
            model_name="team",
            name="handicap",
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("best-ball", "Best Ball"),
                    ("stroke", "Stroke"),
                    ("skins", "Skins"),
                    ("best-ball-skins", "Best Ball w/Skins"),
                    ("stroke-skins", "Stroke w/Skins"),
                ],
                default="stroke",
                max_length=32,
            ),
        ),
    ]
