# Generated by Django 4.2.5 on 2023-12-27 18:17

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_game_buy_in_currency_alter_game_buy_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="Pot",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=None,
                default_currency="USD",
                max_digits=10,
                null=True,
                verbose_name="Pot Total",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="pot_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="buy_in",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("10"),
                default_currency="USD",
                max_digits=5,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(10),
                    djmoney.models.validators.MaxMoneyValidator(100),
                ],
                verbose_name="Per-player buy-in",
            ),
        ),
    ]
