# Generated by Django 4.2.5 on 2023-12-27 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_game_pot_game_pot_currency_alter_game_buy_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="Pot",
        ),
        migrations.RemoveField(
            model_name="game",
            name="pot_currency",
        ),
    ]
