# Generated by Django 4.2.5 on 2023-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_team_options_remove_holescore_team_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["game"], "verbose_name_plural": "teams"},
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("best-ball", "Best Ball"),
                    ("stroke", "Stroke"),
                    ("skins", "Skins"),
                    ("stroke-skins", "Stroke w/Skins"),
                ],
                default="stroke",
                max_length=32,
            ),
        ),
    ]
