# Generated by Django 4.2.5 on 2023-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_team_options_alter_game_game_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["handicap"], "verbose_name_plural": "teams"},
        ),
        migrations.AddField(
            model_name="team",
            name="handicap",
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=3),
        ),
    ]
