# Generated by Django 4.2.5 on 2023-12-27 18:37

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_remove_game_pot_remove_game_pot_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="buy_in",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0,
                default=Decimal("10"),
                default_currency="USD",
                max_digits=3,
                validators=[
                    djmoney.models.validators.MinMoneyValidator({"USD": 10}),
                    djmoney.models.validators.MaxMoneyValidator({"USD": 100}),
                ],
                verbose_name="Per-player buy-in",
            ),
        ),
    ]
