# Generated by Django 4.2.5 on 2023-12-27 19:11

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_alter_game_buy_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="buy_in_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD $")], default="USD", editable=False, max_length=3
            ),
        ),
    ]
