# Generated by Django 4.2.5 on 2023-12-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_alter_game_buy_in_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="setup",
                max_length=64,
            ),
        ),
    ]
