# Generated by Django 4.2.5 on 2024-01-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="score",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
