# Generated by Django 4.2.5 on 2024-01-10 14:02

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_playermembership_in_skins"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playermembership",
            old_name="in_skins",
            new_name="skins",
        ),
        migrations.AddField(
            model_name="game",
            name="skin_cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0,
                default=Decimal("1"),
                default_currency="USD",
                max_digits=2,
                validators=[
                    djmoney.models.validators.MinMoneyValidator({"USD": 1}),
                    djmoney.models.validators.MaxMoneyValidator({"USD": 10}),
                ],
                verbose_name="Per-hole skin cost",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="skin_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD $")], default="USD", editable=False, max_length=3
            ),
        ),
    ]
