# Generated by Django 4.2.5 on 2024-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_rename_in_skins_playermembership_skins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playermembership",
            name="skins",
            field=models.BooleanField(default=True),
        ),
    ]
