# Generated by Django 4.2.5 on 2024-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_alter_playermembership_skins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playermembership",
            name="skins",
            field=models.BooleanField(default=False),
        ),
    ]
