# Generated by Django 4.2.5 on 2024-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_alter_playermembership_skins"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="use_teams",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("best-ball", "Best Ball"),
                    ("points", "Points"),
                    ("stroke", "Stroke"),
                    ("skins", "Skins"),
                    ("best-ball-skins", "Best Ball w/Skins"),
                    ("points-skins", "Points w/Skins"),
                    ("stroke-skins", "Stroke w/Skins"),
                ],
                default="best-ball",
                max_length=32,
            ),
        ),
    ]
