# Generated by Django 4.2.5 on 2024-03-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_game_payout_positions_alter_game_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("best-ball", "Best Ball"),
                    ("stableford", "Stableford"),
                    ("stroke", "Stroke"),
                    ("skins", "Skins"),
                    ("best-ball-skins", "Best Ball w/Skins"),
                    ("stableford-skins", "Stableford w/Skins"),
                    ("stroke-skins", "Stroke w/Skins"),
                ],
                default="stableford-skins",
                max_length=32,
            ),
        ),
    ]
