# Generated by Django 4.2.5 on 2024-03-06 19:28

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_alter_game_game_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="use_skins",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("best-ball", "Best Ball"),
                    ("stableford", "Stableford"),
                    ("stroke", "Stroke"),
                ],
                default="stableford",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="skin_cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=2,
                validators=[
                    djmoney.models.validators.MinMoneyValidator({"USD": 0}),
                    djmoney.models.validators.MaxMoneyValidator({"USD": 10}),
                ],
                verbose_name="Per-hole skin cost",
            ),
        ),
    ]
