# Generated by Django 4.2.5 on 2024-03-09 13:56

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0020_game_use_skins_alter_game_game_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["handicap", "last_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="playermembership",
            name="current_handicap",
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="game",
            name="skin_cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0,
                default=Decimal("1"),
                default_currency="USD",
                max_digits=2,
                validators=[
                    djmoney.models.validators.MinMoneyValidator({"USD": 0}),
                    djmoney.models.validators.MaxMoneyValidator({"USD": 10}),
                ],
                verbose_name="Per-hole skin cost",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("first_name", "last_name")},
        ),
        migrations.RemoveField(
            model_name="player",
            name="name",
        ),
    ]
