# Generated by Django 4.2.5 on 2024-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0021_alter_player_options_alter_player_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
