# Generated by Django 4.2.5 on 2024-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0022_player_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
    ]
