# Generated by Django 4.2.5 on 2024-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0024_alter_player_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="league_game",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="playermembership",
            name="game_handicap",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
