# Generated by Django 4.2.5 on 2024-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0025_game_league_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="previous_handicap",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=None, max_digits=3, null=True
            ),
        ),
    ]
