# Generated by Django 4.2.5 on 2024-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0028_alter_holescore_options_remove_holescore_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holescore",
            name="score",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (-3, "Albatross"),
                    (-2, "Eagle"),
                    (-1, "Birdie"),
                    (0, "Par"),
                    (1, "Bogey"),
                    (2, "Double Bogey"),
                    (3, "Triple Bogey"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="holescore",
            name="points",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, " 0"),
                    (1, " 1"),
                    (2, " 2"),
                    (3, " 3"),
                    (4, " 4"),
                    (5, " 5"),
                    (6, " 6"),
                    (7, " 7"),
                    (8, " 8"),
                    (9, " 9"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="holescore",
            name="strokes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, " 0"),
                    (1, " 1"),
                    (2, " 2"),
                    (3, " 3"),
                    (4, " 4"),
                    (5, " 5"),
                    (6, " 6"),
                    (7, " 7"),
                    (8, " 8"),
                    (9, " 9"),
                ],
                default=0,
            ),
        ),
    ]
