# Generated by Django 4.2.5 on 2024-03-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0029_holescore_score_alter_holescore_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dashboard.golfcourse"
            ),
        ),
    ]
