# Generated by Django 5.1.2 on 2024-10-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_game_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='dashboard.golfcourse'),
        ),
    ]
