# Generated by Django 5.1.2 on 2024-10-31 13:00

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_game_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='course',
            field=models.ForeignKey(default=dashboard.models.get_ttcc_course, on_delete=django.db.models.deletion.PROTECT, to='dashboard.golfcourse'),
        ),
    ]
