# Generated by Django 5.1.2 on 2024-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_game_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='scores',
            field=models.JSONField(default='[]'),
        ),
    ]
