# Generated by Django 5.1.2 on 2024-11-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_player_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
