# Generated by Django 5.1.2 on 2024-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_player_league_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='handicap',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1'), (2, ' 2'), (3, ' 3'), (4, ' 4'), (5, ' 5'), (6, ' 6'), (7, ' 7'), (8, ' 8'), (9, ' 9'), (10, ' 10'), (11, ' 11'), (12, ' 12'), (13, ' 13'), (14, ' 14'), (15, ' 15'), (16, ' 16'), (17, ' 17'), (18, ' 18')], default=1),
        ),
        migrations.AlterField(
            model_name='hole',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1'), (2, ' 2'), (3, ' 3'), (4, ' 4'), (5, ' 5'), (6, ' 6'), (7, ' 7'), (8, ' 8'), (9, ' 9'), (10, ' 10'), (11, ' 11'), (12, ' 12'), (13, ' 13'), (14, ' 14'), (15, ' 15'), (16, ' 16'), (17, ' 17'), (18, ' 18')], default=1),
        ),
        migrations.AlterField(
            model_name='hole',
            name='par',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Par 3'), (4, 'Par 4'), (5, 'Par 5')], default=4),
        ),
    ]
