# Generated by Django 5.1.2 on 2024-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_hole_handicap_alter_hole_order_alter_hole_par'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'players'},
        ),
        migrations.AlterField(
            model_name='tee',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('gold', 'Gold'), ('white', 'White'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange')], default='black', max_length=6, verbose_name='Tee Color'),
        ),
        migrations.AlterField(
            model_name='teetime',
            name='which_holes',
            field=models.CharField(choices=[('all', 'All'), ('front', 'Front 9'), ('back', 'Back 9')], default='all', max_length=5),
        ),
    ]
