# Generated by Django 5.1.2 on 2024-11-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_game_options_alter_golfcourse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['game', 'name'], 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='playermembership',
            order_with_respect_to='game',
        ),
        migrations.AlterUniqueTogether(
            name='playermembership',
            unique_together={('game', 'player')},
        ),
    ]
