# Generated by Django 5.1.2 on 2024-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_player_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holescore',
            name='score',
        ),
        migrations.AddField(
            model_name='holescore',
            name='is_scored',
            field=models.BooleanField(default=False),
        ),
    ]
