# Generated by Django 5.1.2 on 2024-11-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_holescore_options_remove_holescore_is_scored_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holescore',
            options={'ordering': ['player', 'hole', '-strokes'], 'verbose_name_plural': 'scores'},
        ),
    ]
