# Generated by Django 5.1.2 on 2024-11-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_holescore_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='holes_played',
            new_name='holes_to_play',
        ),
    ]
