# Generated by Django 5.1.2 on 2024-12-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_rename_holes_played_game_holes_to_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='previous_handicap',
        ),
    ]
