# Generated by Django 4.2.5 on 2023-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_golfcourse_hole_count_alter_tee_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfcourse",
            name="card",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AddField(
            model_name="golfcourse",
            name="overview",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AddField(
            model_name="hole",
            name="photo",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AddField(
            model_name="player",
            name="photo",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="hole",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="hole",
            name="par",
            field=models.PositiveSmallIntegerField(
                choices=[(3, "3"), (4, "4"), (5, "5")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="holescore",
            name="score",
            field=models.IntegerField(
                choices=[
                    (-3, "Albatross"),
                    (-2, "Eagle"),
                    (-1, "Birdie"),
                    (0, "Par"),
                    (1, "Bogey"),
                    (2, "Double Bogey"),
                    (3, "Triple Bogey"),
                ],
                default=(0, "Par"),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hole",
            unique_together={("order", "course")},
        ),
    ]
