# Generated by Django 4.2.5 on 2023-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_golfcourse_card_alter_golfcourse_overview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfcourse",
            name="card",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="golfcourse",
            name="overview",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="hole",
            name="photo",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
    ]
