# Generated by Django 4.2.5 on 2023-10-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_hole_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="handicap",
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=3),
        ),
    ]
