# Generated by Django 4.2.5 on 2023-10-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0010_alter_player_handicap"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("name", "handicap", "added_by")},
        ),
        migrations.AlterUniqueTogether(
            name="tee",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="game",
            name="league_game",
        ),
        migrations.AddField(
            model_name="tee",
            name="color",
            field=models.CharField(
                choices=[
                    ("BLACK", "Black"),
                    ("BLUE", "Blue"),
                    ("GOLD", "Gold"),
                    ("WHITE", "White"),
                    ("RED", "Red"),
                ],
                default="BLUE",
                max_length=5,
                verbose_name="Tee Color",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="user_account",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="distance",
            field=models.CharField(max_length=3, verbose_name="Tee to Hole Distance"),
        ),
        migrations.AlterUniqueTogether(
            name="tee",
            unique_together={("color", "hole")},
        ),
        migrations.RemoveField(
            model_name="tee",
            name="name",
        ),
    ]
