# Generated by Django 4.2.5 on 2023-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_player_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holescore",
            name="score",
            field=models.IntegerField(
                choices=[
                    (-3, "Albatross"),
                    (-2, "Eagle"),
                    (-1, "Birdie"),
                    (0, "Par"),
                    (1, "Bogey"),
                    (2, "Double Bogey"),
                    (3, "Triple Bogey"),
                ],
                default=(0, "Par"),
            ),
        ),
    ]
