# Generated by Django 4.2.5 on 2023-10-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_holescore_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="holes_played",
            field=models.PositiveSmallIntegerField(
                choices=[(9, "9 Holes"), (18, "18 Holes")], default=18
            ),
        ),
        migrations.AlterField(
            model_name="golfcourse",
            name="hole_count",
            field=models.PositiveSmallIntegerField(
                choices=[(9, "9 Holes"), (18, "18 Holes")], default=18
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="distance",
            field=models.CharField(max_length=3, verbose_name="Tee distance in yards"),
        ),
        migrations.AlterField(
            model_name="teetime",
            name="holes_to_play",
            field=models.PositiveSmallIntegerField(
                choices=[(9, "9 Holes"), (18, "18 Holes")], default=18
            ),
        ),
    ]
