# Generated by Django 4.2.5 on 2023-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_game_holes_played_alter_golfcourse_hole_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hole",
            name="name",
        ),
        migrations.AlterField(
            model_name="holescore",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("blue", "Blue"),
                    ("gold", "Gold"),
                    ("white", "White"),
                    ("red", "Red"),
                ],
                default="blue",
                max_length=5,
                verbose_name="Tee Color",
            ),
        ),
    ]
