# Generated by Django 4.2.5 on 2023-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_remove_hole_name_alter_holescore_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hole",
            name="handicap",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                ],
                default=(1, "1"),
            ),
        ),
        migrations.AlterField(
            model_name="hole",
            name="order",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                ],
                default=(1, "1"),
            ),
        ),
        migrations.AlterField(
            model_name="hole",
            name="par",
            field=models.PositiveSmallIntegerField(
                choices=[(3, "3"), (4, "4"), (5, "5")], default=(3, "3")
            ),
        ),
        migrations.AlterField(
            model_name="holescore",
            name="score",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                default=(1, "1"),
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("blue", "Blue"),
                    ("gold", "Gold"),
                    ("white", "White"),
                    ("red", "Red"),
                ],
                default=("blue", "Blue"),
                max_length=5,
                verbose_name="Tee Color",
            ),
        ),
        migrations.AlterField(
            model_name="teetime",
            name="tee_time",
            field=models.DateTimeField(default="11-02-2023 08:10"),
        ),
    ]
