# Generated by Django 4.2.5 on 2023-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_hole_handicap_alter_hole_order_alter_hole_par_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teetime",
            name="which_holes",
            field=models.CharField(
                choices=[("all", "All"), ("front", "Front"), ("back", "Back")],
                default=("all", "All"),
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="hole",
            name="handicap",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                ],
                default=(1, "1"),
            ),
        ),
        migrations.AlterField(
            model_name="hole",
            name="par",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(3, "3"), (4, "4"), (5, "5")], default=(3, "3")
            ),
        ),
        migrations.AlterField(
            model_name="teetime",
            name="tee_time",
            field=models.DateTimeField(default="11-05-2023 18:46"),
        ),
    ]
