# Generated by Django 4.2.5 on 2023-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_teetime_which_holes_alter_hole_handicap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teetime",
            name="tee_time",
            field=models.DateTimeField(default="11-07-2023 08:04"),
        ),
    ]
