# Generated by Django 4.2.5 on 2023-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_alter_teetime_tee_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teetime",
            name="tee_time",
            field=models.DateTimeField(default="11-10-2023 08:36"),
        ),
    ]
